/* GENERATED by tools/build-map.mjs — do not hand-edit.
 *
 * A real, simplified outline of South Africa (public-domain GeoJSON) projected
 * into a 1000x860 viewBox, plus the seven workshop towns at their true
 * coordinates. `key` matches MAKERS in catalogue.js, so a pin can drive the
 * same filter the shop sidebar does.
 *
 * Projection is equirectangular with a cos(-28.5°) correction on x,
 * without which the country renders too wide.
 */
const MAP_VIEWBOX = '0 0 1000 860';
const MAP_PATH = 'M887 480.9L876.1 490.1L852.4 522.3L836.8 555L805.2 600.5L702.7 704L660.6 732.9L602.2 757.6L573.8 760.9L566.6 778.5L532.7 769.1L505 781.2L444.5 768.9L410.7 776.7L387.6 773.4L330.1 798.4L282.4 808.5L247.9 832.5L222.5 834L198.9 811.4L180.1 810.2L156 781.9L153.4 790.7L146 773.6L146.3 736.4L128.2 693.8L146.2 682.3L144.7 633.6L108.2 574.1L40 437.7L66.7 406.3L88.7 423.7L98.1 450.8L123.2 455.5L158.3 467.5L188.3 462.8L238.1 430.4L238.1 195.9L253.2 205.4L286.3 265.8L281.2 304.4L293.6 326.7L333.6 320.3L361.5 291.9L387.9 272.8L401.6 242.4L428.8 227.7L452.3 235.4L479 253.2L524.4 256.3L560.1 241.6L575.6 191.4L605.9 186.3L622.7 162.4L641.3 120.1L691.4 72.8L770.4 26L793.1 26.7L820.1 37.4L838.9 29.8L868.6 36.2L909.8 170.6L899.9 241.4L904.7 264.2L876.5 252.6L860.4 257.1L855.1 275.6L839.9 299.4L840.4 321.4L873.7 355.8L906.4 348.9L917.7 320.7L960 321.3L946.1 367.5L939.5 420.2L925.1 448.9L887 480.9ZM745.1 461.8L720.7 442.2L694.6 455.2L664.4 480L634.6 520.2L676.5 569L696.4 562.7L706.7 542.4L737.8 532.5L764.4 480.9L745.1 461.8Z';
const MAP_TOWNS = [
  {
    "key": "mokoena",
    "label": "Newtown, Johannesburg",
    "lat": -26.2041,
    "lon": 28.0333,
    "x": 692.3,
    "y": 287.1
  },
  {
    "key": "vaal",
    "label": "Vereeniging",
    "lat": -26.6731,
    "lon": 27.9261,
    "x": 686.3,
    "y": 316.9
  },
  {
    "key": "thabang",
    "label": "Mbombela",
    "lat": -25.4753,
    "lon": 30.9694,
    "x": 856.2,
    "y": 240.8
  },
  {
    "key": "ndlovu",
    "label": "Umbilo, Durban",
    "lat": -29.87,
    "lon": 30.99,
    "x": 857.3,
    "y": 519.8
  },
  {
    "key": "karoo",
    "label": "Graaff-Reinet",
    "lat": -32.252,
    "lon": 24.5308,
    "x": 496.8,
    "y": 671
  },
  {
    "key": "cederberg",
    "label": "Clanwilliam",
    "lat": -32.1833,
    "lon": 18.8833,
    "x": 181.6,
    "y": 666.7
  },
  {
    "key": "saltgrain",
    "label": "Salt River, Cape Town",
    "lat": -33.927,
    "lon": 18.465,
    "x": 158.3,
    "y": 777.4
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { MAP_VIEWBOX, MAP_PATH, MAP_TOWNS };
}
